;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
+GameplayTagRedirects=(OldTagName="Monster.CoolDown.Skill1",NewTagName="Monster.CoolDown.ProjectileSkill")
+GameplayTagRedirects=(OldTagName="Monster.CoolDown.Skill2",NewTagName="Monster.CoolDown.MagicFloorSkill")
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Data.LoadData.HP",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Monster.Skill.Fire",DevComment="Lich 발사체 스킬 Cue")
+GameplayTagList=(Tag="Monster.Ability.Attack",DevComment="")
+GameplayTagList=(Tag="Monster.CoolDown.MagicFloorSkill",DevComment="")
+GameplayTagList=(Tag="Monster.CoolDown.ProjectileSkill",DevComment="")
+GameplayTagList=(Tag="Monster.CoolDown.TeleportSkill",DevComment="")
+GameplayTagList=(Tag="Monster.Cue.Attack",DevComment="")
+GameplayTagList=(Tag="Monster.Cue.Stun",DevComment="")
+GameplayTagList=(Tag="Monster.Data.CoolDown",DevComment="")
+GameplayTagList=(Tag="Monster.Data.CoolDown.MagicFloor",DevComment="")
+GameplayTagList=(Tag="Monster.Data.CoolDown.Projectile",DevComment="")
+GameplayTagList=(Tag="Monster.Data.CoolDown.Teleport",DevComment="")
+GameplayTagList=(Tag="Monster.Data.Damage",DevComment="")
+GameplayTagList=(Tag="Monster.State.Death",DevComment="")
+GameplayTagList=(Tag="Monster.State.Stun",DevComment="")
+GameplayTagList=(Tag="NPC.Emotion.Disappointed",DevComment="NPC가 실망하는 상태")
+GameplayTagList=(Tag="NPC.Emotion.Happy",DevComment="NPC가 즐거워하는 상태")
+GameplayTagList=(Tag="NPC.Emotion.None",DevComment="")
+GameplayTagList=(Tag="NPC.Emotion.Scared",DevComment="NPC가 벌벌떠는 상태")
+GameplayTagList=(Tag="NPC.Emotion.Tired",DevComment="NPC가 지친 상태")

[/Script/GameplayTags.GameplayTagsList]
+GameplayTags=(Tag="Player.State.Rolling", DevComment="플레이어가 구르는 상태")
+GameplayTags=(Tag="Player.State.StaminaRegenDelay", DevComment="플레이어 스테미나 회복대기상태")
+GameplayTags=(Tag="Player.State.Healing", DevComment="플레이어 HP를 회복하는 상태")
+GameplayTags=(Tag="Player.State.Hit", DevComment="플레이어가 맞는상태")
+GameplayTags=(Tag="Player.State.Death", DevComment="플레이어가 죽은상태")

+GameplayTags=(Tag="Player.Skill.Active01", DevComment="플레이어 Skill01 사용")

+GameplayTags=(Tag="Player.Combat", DevComment="플레이어의 모든 공격")
+GameplayTags=(Tag="Player.Combat.Attacking1", DevComment="플레이어 일반공격 1번째")
+GameplayTags=(Tag="Player.Combat.Attacking2", DevComment="플레이어 일반공격 2번째")
+GameplayTags=(Tag="Player.Combat.Attacking3", DevComment="플레이어 일반공격 3번째")
+GameplayTags=(Tag="Player.Combat.Attacking4", DevComment="플레이어 일반공격 4번째")

+GameplayTags=(Tag="Data.Rolling.StaminaCost", DevComment="구르기 스테미나 비용")
+GameplayTags=(Tag="Data.Attacking.StaminaCost", DevComment="일반공격 스테미나 비용")
+GameplayTags=(Tag="Data.Skill.01Cost", DevComment="스킬1 스테미나 비용")
+GameplayTags=(Tag="Data.Skill.01Cooldown", DevComment="스킬1 쿨타임")
+GameplayTags=(Tag="Data.NormalAttack.Damage", DevComment="일반공격 데미지")
+GameplayTags=(Tag="Data.Skill01.Damage", DevComment="스킬1 데미지")

+GameplayTags=(Tag="Event.ComboWindow.Open", DevComment="일반공격 콤보입력 시작")
+GameplayTags=(Tag="Event.ComboWindow.2", DevComment="일반공격2 콤보입력 시작")
+GameplayTags=(Tag="Event.ComboWindow.3", DevComment="일반공격3 콤보입력 시작")
+GameplayTags=(Tag="Event.AttackInput.Block", DevComment="공격 입력 차단")
+GameplayTags=(Tag="Event.ComboWindow.Close", DevComment="일반공격 콤보입력 종료")

+GameplayTags=(Tag="GameplayCue.Player.Attack.BP_NormalAttackCue", DevComment="플레이어 일반공격 큐")
+GameplayTags=(Tag="GameplayCue.Player.Skill", DevComment="플레이어 스킬 큐")

